#!/bin/bash
source ./helpers/bash.sh
echo ""

if [ -z "$(localcert_installed)" ]; then
	echo "-> Downloading mkcert"
	if [ -n "$(localcert_download)" ]; then
		echo "   Done"
		echo ""
	else
		echo "   Failed"
		echo ""
		exit 1
	fi
fi

if [ -z "$(localcert_root_path)" ]; then
	echo "-> Installing rootCA"
	localcert_exec -install
	if [ -n "$(localcert_root_path)" ]; then
		echo "   Done"
		echo ""
	else
		echo "   Skipped (already installed)"
		echo ""
	fi
fi

if [ -z "$1" ] && [ -z "$2" ]; then
	echo "Usage"
	echo "====="
	echo ""
	echo "localcert <certname> <domain.tld>"
	echo ""
	exit 0
fi

echo "-> Generate certificate"
localcert_generate "$1" "$2"
echo "   Done"
echo ""